server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: webapp
    static_configs:
      - targets:
          - "localhost"
        labels:
          webapp: varlogs          
          __path__: /var/log/webapp.log