services:  
  web:  
    container_name: app      
    build: .
    ports:
      - "${HOST_PORT:-8080}:${APP_PORT:-5000}"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  redis: 
    container_name: redis  
    image: redis:7.4-alpine3.20  
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli ping || exit 1
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  redis_data: