---
- name: Add PHP repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present
  become: true

- name: Install the GPG key for Node.js LTS
  ansible.builtin.apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  become: true

- name: Install the Node.js LTS repository
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  become: true

- name: Install Node.js and Apache
  ansible.builtin.apt:
    name:
      - apache2
      - nodejs
    state: present
  become: true

- name: Install PHP 8.2 and its dependencies
  ansible.builtin.apt:
    name:
      - php8.2
      - php8.2-cli
      - php8.2-curl
      - php8.2-bz2
      - php8.2-mbstring
      - php8.2-intl
      - php8.2-xml
      - php8.2-mysql
      - php8.2-pgsql
    state: present
  become: true

- name: Install Composer
  ansible.builtin.get_url:
    url: https://getcomposer.org/download/latest-stable/composer.phar
    dest: /usr/local/bin/composer
    mode: '0755'
  become: true
