services:

  webapp:
    build: .
    container_name: webapp
    ports: 
      - "8080:8080"
    environment:
      PORT: "8080" 
      LOG_PATH: "/var/log/webapp.log"
    volumes:
      - webapp_logs:/var/log

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki_config.yaml
    volumes:
      - ./monitoring/loki_config.yaml:/etc/loki/loki_config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: -config.file=/etc/promtail/static_config.yaml
    volumes:
      - ./monitoring/promtail/static_config.yaml:/etc/promtail/static_config.yaml
      - webapp_logs:/var/log
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "9090:3000"
    command: --config=/etc/grafana/grafana.ini
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - loki
      - promtail

volumes:
  webapp_logs: