- name: "Ensure remote connection to database are allowed."
  community.postgresql.postgresql_set:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ postgresql_options }}"
  become: true
  become_user: "{{ postgresql_system_user }}"
  notify:
    - restart postgres