- name: Ensure databases are present.
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    encoding: "UTF-8"
    state: present
  loop: "{{ postgresql_databases }}"
  become: true
  become_user: "{{ postgresql_system_user }}"
