- name: "Ensure PostgreSQL users privileges are configured correctly."
  community.postgresql.postgresql_privs:
    database: "{{ item.db }}"
    privs: "{{ item.privs }}"
    type: "{{ item.type | default(omit) }}"
    roles: "{{ item.roles | default(omit) }}"
    state: present
  loop: "{{ postgresql_privs | default([]) }}"
  become: true
  become_user: "{{ postgresql_system_user }}"
  notify:
    - restart postgres

- name: "Ensure host-based configuration file (pg_hba.conf) is created."
  community.postgresql.postgresql_pg_hba:
    dest: "{{ postgresql_config_dir }}/pg_hba.conf"
    address: "{{ item.address | default(omit) }}"
    contype: "{{ item.contype }}"
    databases: "{{ item.databases }}"
    method: "{{ item.method }}"
    users: "{{ item.users }}"
    create: true
  loop: "{{ postgresql_hba_entries }}"
  become: true
  become_user: "{{ postgresql_system_user }}"
  notify:
    - restart postgres


