services:

  webapp:
    build: .
    container_name: webapp
    ports: 
      - "8080:8080"
    environment:
      PORT: "8080" 
    labels:
      logging: "promtail"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki_config.yaml
    volumes:
      - ./monitoring/loki_config.yaml:/etc/loki/loki_config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: -config.file=/etc/promtail/docker_sd_config.yaml
    volumes:
      - ./monitoring/promtail/docker_sd_config.yaml:/etc/promtail/docker_sd_config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "9090:3000"
    command: --config=/etc/grafana/grafana.ini
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - loki
      - promtail

