name: CI Maven Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
   
    strategy:
      matrix:
        os: [ubuntu-22.04]
        java-version: ['8.x', '11.x', '17.x']
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run tests
      run: mvn test -Dapp.port=$APP_PORT
      env: 
        APP_PORT: 8080

    - name: Create test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test report JDK ${{ matrix.java-version }}, ${{ matrix.os }}
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
