plugin: aws_ec2
regions: 
- us-east-1
filters:
  instance-state-name: running
  "tag:project": ansible_project

keyed_groups:
  - key: tags.type
    prefix: "type"
  - key: tags.project:ansible_project
    prefix: "aws"

hostnames:
  - tag:Name
compose:
  ansible_host: public_dns_name